import {NextResponse} from "next/server";import {z} from "zod";import JSZip from "jszip";import {createClient} from "@/lib/supabase/server";import {createAdminClient} from "@/lib/supabase/admin";import {dispatchBuild} from "@/lib/github";
export const runtime="nodejs";
const bool=z.preprocess(v=>v==="true"||v===true,z.boolean());
const permissionSchema=z.object({camera:z.boolean(),microphone:z.boolean(),location:z.boolean(),notifications:z.boolean(),vibrate:z.boolean()});
const schema=z.object({name:z.string().trim().min(2).max(40),packageName:z.string().regex(/^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+$/),mode:z.enum(["url","zip"]),sourceUrl:z.string().optional(),versionName:z.string().regex(/^\d+(\.\d+){0,2}$/),versionCode:z.coerce.number().int().positive(),orientation:z.enum(["portrait","landscape","unspecified"]),themeColor:z.string().regex(/^#[0-9a-fA-F]{6}$/),permissions:z.string().transform(v=>permissionSchema.parse(JSON.parse(v))),notificationEnabled:bool,welcomeNotificationEnabled:bool,fullscreen:bool,allowZoom:bool,oneSignalAppId:z.string().trim().max(80).optional(),welcomeTitle:z.string().trim().max(50).optional(),welcomeBody:z.string().trim().max(160).optional(),customUserAgent:z.string().trim().max(180).optional()});
export async function POST(request:Request){const sb=await createClient();const {data:{user}}=await sb.auth.getUser();if(!user)return NextResponse.json({error:"Unauthorized"},{status:401});try{const form=await request.formData();const parsed=schema.parse(Object.fromEntries(form.entries()));const admin=createAdminClient(),id=crypto.randomUUID();let sourcePath:string|null=null,sourceFileName:string|null=null,dispatchSource=parsed.sourceUrl||"",iconPath:string|null=null,iconUrl="";
 if(parsed.mode==="url"){const url=new URL(dispatchSource);if(url.protocol!=="https:")throw new Error("URL website wajib menggunakan HTTPS")}else{const file=form.get("sourceFile");if(!(file instanceof File)||!file.size)throw new Error("File ZIP atau HTML wajib dipilih");if(file.size>50*1024*1024)throw new Error("Ukuran source maksimal 50 MB");sourceFileName=file.name;let payload:Blob=file;if(/\.html?$/i.test(file.name)){const zip=new JSZip();zip.file("index.html",await file.text());payload=await zip.generateAsync({type:"blob",compression:"DEFLATE",compressionOptions:{level:6}})}else if(!/\.zip$/i.test(file.name))throw new Error("Format source harus ZIP, HTML, atau HTM");sourcePath=`${user.id}/${id}/source.zip`;const {error}=await admin.storage.from("sources").upload(sourcePath,payload,{contentType:"application/zip",upsert:false});if(error)throw error;const {data:signed}=await admin.storage.from("sources").createSignedUrl(sourcePath,86400);if(!signed?.signedUrl)throw new Error("Gagal membuat akses source");dispatchSource=signed.signedUrl}
 const icon=form.get("appIcon");if(icon instanceof File&&icon.size){if(icon.size>2*1024*1024)throw new Error("Ukuran icon maksimal 2 MB");const ext:{[k:string]:string}={"image/png":"png","image/jpeg":"jpg","image/webp":"webp"};const suffix=ext[icon.type];if(!suffix)throw new Error("Icon harus PNG, JPG, atau WebP");iconPath=`${user.id}/${id}/icon.${suffix}`;const {error}=await admin.storage.from("sources").upload(iconPath,icon,{contentType:icon.type,upsert:false});if(error)throw error;const {data:signed}=await admin.storage.from("sources").createSignedUrl(iconPath,86400);iconUrl=signed?.signedUrl||""}
 if(parsed.notificationEnabled&&parsed.oneSignalAppId&&!/^[0-9a-f-]{30,40}$/i.test(parsed.oneSignalAppId))throw new Error("Format OneSignal App ID tidak valid");
 const record={id,user_id:user.id,name:parsed.name,package_name:parsed.packageName,mode:parsed.mode,source_url:parsed.mode==="url"?dispatchSource:null,source_path:sourcePath,source_file_name:sourceFileName,app_icon_path:iconPath,version_name:parsed.versionName,version_code:parsed.versionCode,orientation:parsed.orientation,theme_color:parsed.themeColor,permissions:parsed.permissions,notification_enabled:parsed.notificationEnabled,onesignal_app_id:parsed.oneSignalAppId||null,welcome_notification_enabled:parsed.welcomeNotificationEnabled,welcome_notification_title:parsed.welcomeTitle||null,welcome_notification_body:parsed.welcomeBody||null,fullscreen:parsed.fullscreen,allow_zoom:parsed.allowZoom,custom_user_agent:parsed.customUserAgent||null,status:"queued"};const {error:insertError}=await admin.from("builds").insert(record);if(insertError)throw insertError;
 const config=JSON.stringify({appName:parsed.name,packageName:parsed.packageName,versionName:parsed.versionName,versionCode:parsed.versionCode,orientation:parsed.orientation,themeColor:parsed.themeColor,iconUrl,permissions:parsed.permissions,notificationEnabled:parsed.notificationEnabled,oneSignalAppId:parsed.oneSignalAppId||"",welcomeNotificationEnabled:parsed.welcomeNotificationEnabled,welcomeTitle:parsed.welcomeTitle||"",welcomeBody:parsed.welcomeBody||"",fullscreen:parsed.fullscreen,allowZoom:parsed.allowZoom,customUserAgent:parsed.customUserAgent||""});try{await dispatchBuild({build_id:id,user_id:user.id,mode:parsed.mode,source:dispatchSource,config})}catch(error){await admin.from("builds").update({status:"failed",error_message:error instanceof Error?error.message:"Dispatch gagal"}).eq("id",id);throw error}return NextResponse.json({id},{status:201})}catch(error){if(error instanceof z.ZodError)return NextResponse.json({error:error.issues[0]?.message||"Data tidak valid"},{status:400});return NextResponse.json({error:error instanceof Error?error.message:"Terjadi kesalahan"},{status:400})}}
