import type {Metadata} from "next";import Link from "next/link";import {ArrowRight,Bell,Check,ChevronRight,FileArchive,Fingerprint,Github,Image as ImageIcon,LockKeyhole,ShieldCheck,Sparkles,Smartphone,WandSparkles} from "lucide-react";import {SiteFooter,SiteHeader} from "@/components/site-chrome";
export const metadata:Metadata={alternates:{canonical:"https://web2apk.xystudio.my.id"}};
const featureGroups=[
 {icon:FileArchive,title:"Smart source detection",desc:"Upload ZIP atau HTML. Sistem membaca judul, nama file, dan menyiapkan konfigurasi otomatis."},
 {icon:ImageIcon,title:"Branding lengkap",desc:"Icon aplikasi, nama, package ID, version name, version code, warna tema, dan orientasi."},
 {icon:Bell,title:"Push notification",desc:"Integrasi OneSignal opsional untuk push notification custom langsung ke pengguna aplikasi."},
 {icon:Fingerprint,title:"Permission control",desc:"Pilih akses kamera, mikrofon, lokasi, notifikasi, getar, dan jaringan sesuai kebutuhan."},
 {icon:Github,title:"Cloud Android builder",desc:"Build aman dan terisolasi dengan GitHub Actions, Gradle, signing key, serta private artifact."},
 {icon:ShieldCheck,title:"Private by default",desc:"Row Level Security dan signed URL menjaga source maupun APK tetap milik akun Anda."},
];
export default function Home(){return <main className="mesh min-h-screen"><SiteHeader/><section className="relative mx-auto max-w-7xl px-5 pb-24 pt-20 sm:px-7 lg:pb-32 lg:pt-28"><div className="pointer-events-none absolute left-1/2 top-16 h-96 w-96 -translate-x-1/2 rounded-full bg-white/[.07] blur-[110px]"/><div className="enter relative mx-auto max-w-4xl text-center"><div className="inline-flex items-center gap-2 border border-white/10 bg-white/[.04] px-3 py-1.5 text-[10px] font-black uppercase tracking-[.16em] text-zinc-400 backdrop-blur-xl"><Sparkles size={12}/> Build lebih pintar. Tanpa setup Android Studio.</div><h1 className="mt-8 text-[3.2rem] font-black leading-[.94] tracking-[-.065em] sm:text-7xl lg:text-[6.4rem]">Web kamu.<br/><span className="text-zinc-500">Sekarang aplikasi.</span></h1><p className="mx-auto mt-7 max-w-2xl text-base leading-7 text-zinc-500 sm:text-lg">Ubah URL, HTML, atau ZIP menjadi APK Android. Kontrol identitas, permission, push notification, tampilan, dan signing dari satu builder.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/register" className="btn-primary px-7">Build APK gratis <ArrowRight size={16}/></Link><Link href="#features" className="btn-secondary px-7">Jelajahi fitur</Link></div><div className="mt-7 flex flex-wrap justify-center gap-x-5 gap-y-2 text-[11px] text-zinc-600">{["Source tetap private","URL & offline HTML","APK siap install"].map(x=><span key={x} className="flex items-center gap-1.5"><Check size={12}/>{x}</span>)}</div></div>
<div className="enter enter-delay-2 relative mx-auto mt-20 max-w-5xl"><div className="absolute -inset-12 bg-white/[.035] blur-[90px]"/><div className="glass relative overflow-hidden rounded-lg"><div className="flex h-12 items-center justify-between border-b border-white/[.08] px-4"><div className="flex gap-1.5"><i className="h-2 w-2 bg-zinc-700"/><i className="h-2 w-2 bg-zinc-700"/><i className="h-2 w-2 bg-zinc-500"/></div><span className="text-[10px] text-zinc-700">web2apk.xystudio.my.id/dashboard/new</span><LockKeyhole size={12} className="text-zinc-700"/></div><div className="grid min-h-[430px] md:grid-cols-[190px_1fr]"><aside className="hidden border-r border-white/[.07] bg-black/20 p-4 md:block"><div className="mb-6 h-8 w-28 bg-white/[.07]"/>{["Overview","Source","Branding","Capability","Build"].map((x,i)=><div key={x} className={`mb-2 flex items-center gap-2 px-3 py-2 text-[11px] ${i===2?"bg-white text-black":"text-zinc-600"}`}><i className={`h-1.5 w-1.5 ${i===2?"bg-black":"bg-zinc-700"}`}/>{x}</div>)}</aside><div className="p-5 sm:p-8"><div className="flex items-center justify-between"><div><p className="eyebrow">Langkah 2 / 4</p><h3 className="mt-2 text-xl font-black">Identitas aplikasi</h3></div><Smartphone className="text-zinc-600"/></div><div className="mt-7 grid gap-5 sm:grid-cols-[110px_1fr]"><div className="grid aspect-square place-items-center border border-white/10 bg-black/40"><div className="grid h-14 w-14 place-items-center bg-white text-xl font-black text-black">W</div></div><div className="grid gap-4 sm:grid-cols-2"><DemoField label="Judul" value="Katalog Bali"/><DemoField label="Package name" value="id.xystudio.katalog"/><DemoField label="Versi" value="1.0.0"/><DemoField label="Version code" value="1"/></div></div><div className="mt-6 border border-white/[.08] bg-white/[.025] p-4"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><WandSparkles size={17}/><div><p className="text-xs font-bold">Konfigurasi terdeteksi otomatis</p><p className="mt-1 text-[10px] text-zinc-600">Title dan package dibuat dari source HTML</p></div></div><ChevronRight size={15} className="text-zinc-700"/></div></div><div className="mt-7 flex justify-end"><span className="btn-primary">Lanjutkan <ArrowRight size={14}/></span></div></div></div></div></div></section>
<section id="features" className="scroll-reveal border-y border-white/[.07] bg-black/40"><div className="mx-auto max-w-7xl px-5 py-24 sm:px-7"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><div className="max-w-md"><p className="eyebrow">Builder lengkap</p><h2 className="mt-5 text-4xl font-black tracking-[-.045em] sm:text-5xl">Detail kecil yang bikin APK terasa serius.</h2><p className="mt-5 text-sm leading-7 text-zinc-500">Bukan sekadar membungkus URL. Web2APK memberi kontrol terhadap identitas, kapabilitas, distribusi, dan pengalaman aplikasi.</p></div><div className="grid gap-px overflow-hidden border border-white/[.08] bg-white/[.08] sm:grid-cols-2">{featureGroups.map(({icon:Icon,title,desc})=><article key={title} className="bg-[#080808] p-6 transition hover:bg-[#0d0d0d]"><Icon size={21} className="text-zinc-400"/><h3 className="mt-7 text-sm font-black">{title}</h3><p className="mt-2 text-xs leading-6 text-zinc-600">{desc}</p></article>)}</div></div></div></section>
<section className="scroll-reveal mx-auto max-w-7xl px-5 py-24 sm:px-7"><div className="glass grid items-center gap-10 rounded-lg p-7 sm:p-12 lg:grid-cols-[1fr_auto]"><div><p className="eyebrow">Siap membangun?</p><h2 className="mt-4 text-3xl font-black tracking-tight sm:text-4xl">Dari source ke APK dalam satu alur.</h2><p className="mt-3 text-sm text-zinc-500">Mulai dengan URL, ZIP, atau satu file HTML.</p></div><Link href="/register" className="btn-primary">Buat aplikasi <ArrowRight size={16}/></Link></div></section><SiteFooter/></main>}
function DemoField({label,value}:{label:string,value:string}){return <div><p className="mb-2 text-[9px] font-bold uppercase tracking-widest text-zinc-600">{label}</p><div className="border border-white/10 bg-black/45 px-3 py-3 text-xs text-zinc-300">{value}</div></div>}
