export type HelpSection={title:string;body:string;items?:string[]};export type HelpArticle={title:string;description:string;category:string;sections:HelpSection[]};
export const helpArticles:Record<string,HelpArticle>={
"getting-started":{title:"Getting Started",description:"Dari akun baru sampai APK pertama.",category:"Panduan",sections:[{title:"1. Buat dan verifikasi akun",body:"Daftar dengan email aktif, selesaikan verifikasi email, lalu masuk ke workspace. Session disimpan melalui cookie esensial Supabase, bukan berdasarkan alamat IP."},{title:"2. Siapkan source",body:"Pilih URL HTTPS, satu file HTML, ZIP static web, atau project Compose jika akun telah mendapat trusted access.",items:["HTML/ZIP wajib memiliki index.html","URL wajib HTTPS","Project Compose wajib memiliki Gradle wrapper"]},{title:"3. Konfigurasi",body:"Atur identitas, versi, target SDK, permission, storage mode, splash, icon, orientasi, dan capability lain."},{title:"4. Pantau build",body:"Build berjalan di worker terisolasi. Progress dan log dapat dipantau dari halaman sesi /c/{kode}. Setelah selesai, download APK melalui signed link."}]},
"guides":{title:"Guides",description:"Peta seluruh panduan Web2APK.",category:"Panduan",sections:[{title:"Web to APK",body:"Gunakan URL HTTPS untuk aplikasi yang selalu mengikuti perubahan website."},{title:"HTML to APK",body:"Gunakan HTML atau ZIP untuk konten offline yang ikut dibundel ke APK."},{title:"Compose Builder",body:"Trusted users dapat mengirim project Android Studio lengkap. Gradle dijalankan tanpa production secrets pada isolated job."},{title:"Release dan update",body:"Gunakan package name dan signing key yang sama serta naikkan version code pada setiap update."}]},
"build-apk":{title:"Build APK",description:"Cara kerja Android build, signing, dan artifact.",category:"Builder",sections:[{title:"Build pipeline",body:"Source divalidasi, project Android disiapkan, Gradle assembleRelease dijalankan, APK ditandatangani, lalu output diunggah ke private Storage."},{title:"Signing",body:"Production signing memerlukan empat GitHub secrets yang lengkap. Jika tidak lengkap, builder menggunakan debug key untuk testing."},{title:"Build failure",body:"Buka panel Build Log. Potongan Gradle error disimpan untuk membantu diagnosis. Gunakan Build Ulang setelah konfigurasi diperbaiki."}]},
"html-format":{title:"HTML & ZIP Format",description:"Struktur source static yang didukung.",category:"Builder",sections:[{title:"Single HTML",body:"File .html/.htm dibungkus otomatis menjadi index.html."},{title:"ZIP",body:"index.html harus berada di root atau tepat di dalam satu folder pembungkus.",items:["Gunakan path asset relatif","Hindari executable/binary","Optimalkan gambar","Jangan precache video besar"]},{title:"Source security",body:"Extractor menolak path traversal, symbolic link berbahaya, jumlah file berlebihan, dan executable yang tidak diperlukan."}]},
"permissions":{title:"Android Permissions",description:"Pilih permission seminimal mungkin.",category:"Android",sections:[{title:"Permission tersedia",body:"Kamera, mikrofon, lokasi, notifikasi, dan getar dapat dipilih per build."},{title:"Prinsip least privilege",body:"Aktifkan hanya permission yang benar-benar digunakan. Jelaskan alasannya kepada pengguna sebelum sistem menampilkan prompt."},{title:"Tanggung jawab publisher",body:"Pemilik aplikasi bertanggung jawab terhadap consent, privacy disclosure, dan Data Safety Google Play."}]},
"push-notification":{title:"Push Notification",description:"Konfigurasi OneSignal dan notification permission.",category:"Android",sections:[{title:"OneSignal",body:"Masukkan OneSignal App ID, bukan REST API key. Dependency OneSignal hanya dimasukkan saat fitur benar-benar aktif."},{title:"Android 13+",body:"Permission notifikasi harus diminta pada runtime."},{title:"Welcome notification",body:"Notifikasi lokal opsional dapat tampil satu kali setelah aplikasi pertama dibuka."}]},
"storage":{title:"Storage & Data",description:"Mode penyimpanan, cache, dan folder aplikasi.",category:"Android",sections:[{title:"Hemat Storage",body:"Menonaktifkan HTTP cache dan membersihkan cache saat background/close. Direkomendasikan untuk HTML sederhana."},{title:"Normal",body:"Mempertahankan cache dan web data agar login serta loading ulang lebih cepat."},{title:"Private/Ephemeral",body:"Membersihkan cookie dan WebStorage. Mode ini dapat menyebabkan logout."},{title:"Folder data",body:"Pilih internal private, Android/media, app-specific Downloads, atau tanpa folder tambahan."}]},
"signing":{title:"APK Signing",description:"Menjaga identitas dan kemampuan update aplikasi.",category:"Release",sections:[{title:"Production key",body:"Simpan keystore, alias, store password, dan key password secara permanen."},{title:"Update",body:"Android hanya menerima update jika package name dan signing certificate sama, dengan version code lebih tinggi."},{title:"Keamanan",body:"Keystore tidak pernah diberikan kepada untrusted Compose build job. APK ditandatangani pada publish job terpisah."}]},
"update-app":{title:"Update App",description:"Membuat versi baru tanpa mengubah identitas aplikasi.",category:"Release",sections:[{title:"Premium updates",body:"Pro dan Business dapat reuse source/icon, mengubah konfigurasi, dan membuat version code berikutnya tanpa memotong kuota build baru."},{title:"Yang wajib tetap sama",body:"Package name dan signing key harus sama."},{title:"Yang dapat diubah",body:"Source, nama tampilan, versi, icon, permission, splash, target SDK, storage, dan capability dapat diperbarui."}]},
"troubleshooting":{title:"Troubleshooting",description:"Solusi cepat masalah akun, source, dan build.",category:"Bantuan",sections:[{title:"Build queued",body:"Periksa GITHUB_TOKEN, Actions permission, workflow availability, dan kuota provider."},{title:"Required",body:"Buat sesi baru dan pastikan deployment terbaru aktif."},{title:"Data pengguna besar",body:"Gunakan Hemat Storage, uninstall versi lama sebelum test, dan audit IndexedDB/service worker/cache API."},{title:"Duplicate Kotlin",body:"Gunakan template terbaru; OneSignal bersifat conditional dan Kotlin dependency diselaraskan."},{title:"Email tidak masuk",body:"Periksa Auth logs, SMTP, spam, SPF, DKIM, dan DMARC."}]},
"changelog":{title:"Changelog",description:"Ringkasan evolusi Web2APK.",category:"Informasi",sections:[{title:"Juli 2026",body:"SaaS plans, private create sessions, build logs, admin controls, APK-only workflow, storage modes, Help Center, cookie consent, security foundation, trusted Compose worker, target SDK/architecture controls."},{title:"Kebijakan versi",body:"Perubahan besar dicatat per deployment. Database migration selalu additive dan dijalankan berurutan."}]},
"status":{title:"Service Status",description:"Komponen yang memengaruhi layanan.",category:"Informasi",sections:[{title:"Web/API",body:"Berjalan pada Vercel dan custom domains XyStudio."},{title:"Database/Auth/Storage",body:"Disediakan Supabase."},{title:"APK builders",body:"GitHub Actions menjadi primary engine; fallback provider direncanakan."},{title:"Incident",body:"Saat insiden, periksa Vercel deployment, Supabase status, dan GitHub Actions terlebih dahulu."}]},
"contact":{title:"Contact",description:"Kanal dukungan dan keamanan.",category:"Bantuan",sections:[{title:"General support",body:"Gunakan alamat info/support XyStudio setelah email routing aktif. Sertakan build ID dan waktu kejadian tanpa mengirim password atau secret."},{title:"Security",body:"Laporkan vulnerability secara privat. Jangan membuka data pengguna lain atau mempublikasikan exploit sebelum perbaikan."},{title:"Abuse",body:"Laporkan phishing, malware, copyright abuse, dan aplikasi berbahaya beserta bukti yang relevan."}]},
"api-docs":{title:"API Overview",description:"Domain dan endpoint API Web2APK.",category:"Developer",sections:[{title:"Base URL",body:"api.xystudio.my.id digunakan untuk health check, signed APK delivery, build operations, webhooks, dan integrasi server."},{title:"Authentication",body:"Dashboard API memakai secure session. Download public menggunakan short-lived HMAC token. Webhook memakai signature provider."},{title:"Rate limits",body:"Endpoint sensitif dilindungi Upstash Redis ketika credentials dikonfigurasi."}]},
"acceptable-use":{title:"Acceptable Use Policy",description:"Aktivitas yang diizinkan dan dilarang.",category:"Legal",sections:[{title:"Dilarang",body:"Malware, phishing, credential theft, surveillance tanpa izin, spam, pelanggaran hak cipta, eksploitasi anak, penipuan, bypass keamanan, dan beban otomatis yang mengganggu layanan."},{title:"Enforcement",body:"XyStudio dapat menahan build, suspend akun, menghapus artifact, atau melapor kepada pihak berwenang apabila diperlukan."},{title:"Appeal",body:"Pemilik akun dapat mengajukan peninjauan dengan bukti kepemilikan dan tujuan penggunaan yang sah."}]},
"refund-policy":{title:"Refund Policy",description:"Ketentuan refund paket berbayar.",category:"Legal",sections:[{title:"Sebelum pembayaran aktif",body:"Paket berbayar saat ini dapat berstatus waitlist. Tidak ada tagihan sampai payment gateway production diaktifkan."},{title:"Setelah aktif",body:"Refund mengikuti hukum yang berlaku dan kondisi layanan yang tidak diberikan. Kuota yang telah digunakan, biaya processor, dan penyalahgunaan dapat tidak memenuhi syarat."},{title:"Permintaan",body:"Sertakan order ID, email akun, alasan, dan bukti pembayaran. Jangan mengirim data kartu."}]},
"dmca":{title:"Copyright & Takedown",description:"Prosedur laporan hak cipta.",category:"Legal",sections:[{title:"Laporan",body:"Sertakan identitas pemegang hak, karya asli, lokasi konten yang dilaporkan, pernyataan itikad baik, dan informasi kontak."},{title:"Counter notice",body:"Pengguna dapat mengirim bantahan dengan bukti izin atau kepemilikan."},{title:"Repeat infringement",body:"Akun pelanggar berulang dapat ditangguhkan atau dihentikan."}]},
"service-level":{title:"Service Level",description:"Ketersediaan dan batas layanan.",category:"Legal",sections:[{title:"Best effort",body:"Free tier diberikan secara best effort tanpa SLA uptime."},{title:"Dependency",body:"Ketersediaan bergantung pada Vercel, Supabase, GitHub, DNS, dan provider pihak ketiga."},{title:"Maintenance",body:"Maintenance atau emergency mitigation dapat menghentikan build sementara untuk melindungi sistem."}]}
};
