export type BuildStatus = "queued" | "building" | "success" | "failed";
export type BuildMode = "url" | "zip";
export interface Build {
  id: string;
  user_id: string;
  public_code: string | null;
  parent_build_id: string | null;
  name: string;
  package_name: string;
  mode: BuildMode;
  source_url: string | null;
  source_path: string | null;
  version_name: string;
  version_code: number;
  orientation: "portrait" | "landscape" | "unspecified";
  theme_color: string;
  source_file_name: string | null;
  app_icon_path: string | null;
  permissions: Record<"camera" | "microphone" | "location" | "notifications" | "vibrate", boolean>;
  notification_enabled: boolean;
  onesignal_app_id: string | null;
  welcome_notification_enabled: boolean;
  welcome_notification_title: string | null;
  welcome_notification_body: string | null;
  fullscreen: boolean;
  allow_zoom: boolean;
  custom_user_agent: string | null;
  storage_mode: "normal" | "low" | "ephemeral";
  status: BuildStatus;
  apk_path: string | null;
  aab_path: string | null;
  progress: number;
  current_step: string;
  splash_enabled: boolean;
  splash_background: string;
  splash_duration: number;
  expires_at: string | null;
  error_message: string | null;
  created_at: string;
  updated_at: string;
}
